### ISSUE TITLE
RuntimeError: invalid hash value

### ISSUE THREAD

**Issue by wusaifei** [lhwcv/cloud_german_rank10#1]
你好在下载http://data.lip6.fr/cadene/pretrainedmodels/se_resnet50-ce0d4300.pth过程中出现了RuntimeError: invalid hash value   请问一下这个是什么原因？是不是可以直接把se_resnet50-ce0d4300.pth文件添加到.torch/model 中去。
感谢大佬帮忙解答一下

**Comment by lhwcv** [comment]
@wusaifei 下载时网络的问题，一般重新运行下就可以了。 或者可以先wget  http://data.lip6.fr/cadene/pretrainedmodels/se_resnet50-ce0d4300.pth](http://data.lip6.fr/cadene/pretrainedmodels/se_resnet50-ce0d4300.pth
